# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-20 20:44
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Coder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('github', models.CharField(max_length=255)),
                ('linkedin', models.CharField(max_length=255)),
                ('nickname', models.CharField(max_length=255)),
                ('lugarVive', models.CharField(max_length=255)),
                ('disponibilidad', models.CharField(choices=[('remoto', 'remoto'), ('presencial', 'presencial')], default='presencial', max_length=255)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Equipos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreEquipo', models.CharField(max_length=255)),
                ('nombreProyecto', models.CharField(max_length=255)),
                ('descripcionProyecto', models.TextField(default='None')),
                ('participantes', models.ManyToManyField(to='users.Coder')),
            ],
        ),
        migrations.CreateModel(
            name='Lenguaje',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreLenguaje', models.CharField(max_length=255)),
                ('objetivo', models.CharField(choices=[('indefinido', 'indefinido'), ('objetos', 'orientado a objetos'), ('eventos', 'orientado a eventos'), ('hibrido', 'hibrido')], default='indefinido', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Organizador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Reclutador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empresa', models.CharField(max_length=255)),
                ('lugarEmpresa', models.CharField(max_length=255)),
                ('lenguajes', models.ManyToManyField(to='users.Lenguaje')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
