# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-21 01:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20160221_0037'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coder',
            name='nickname',
        ),
    ]
