# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-21 04:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_coder_nickname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coder',
            name='disponibilidad',
            field=models.CharField(choices=[('1', 'remoto'), ('2', 'presencial')], default='2', max_length=255),
        ),
        migrations.AlterField(
            model_name='coder',
            name='tiempo',
            field=models.CharField(choices=[('1', 'completo'), ('2', 'medio tiempo')], default='1', max_length=255),
        ),
    ]
