# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-21 06:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20160221_0441'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipos',
            name='tecnologias',
            field=models.ManyToManyField(to='users.Lenguaje'),
        ),
    ]
