# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-20 20:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hackaton',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreHackaton', models.CharField(max_length=255)),
                ('lugar', models.CharField(max_length=255)),
                ('descripcion', models.TextField(default='None')),
                ('fecha', models.DateTimeField()),
                ('equipos', models.ManyToManyField(to='users.Equipos')),
                ('organizadores', models.ManyToManyField(to='users.Coder')),
            ],
        ),
    ]
