# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-21 00:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hackaton', '0002_auto_20160220_2048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hackaton',
            name='descripcion',
            field=models.TextField(default=''),
        ),
    ]
