# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-21 06:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hackaton', '0003_auto_20160221_0037'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sponsor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('logo', models.ImageField(upload_to='logos/')),
                ('pagina', models.URLField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='hackaton',
            name='sponsores',
            field=models.ManyToManyField(to='hackaton.Sponsor'),
        ),
    ]
